name: Push Mac ARM64 image

on: 
  workflow_dispatch:
  release:
    types: [published]

jobs:
  mac-install-purple:
    runs-on: self-hosted  

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          path: purple-hats
      
      - name: Grant execute permissions for user
        run: chmod ugo+rwx ./scripts/*.command ./scripts/*.sh
        working-directory: purple-hats

      - name: Copy scripts to parent directory
        run: |
          cp ./purple-hats/scripts/{*.command,*.sh,*.xml}  ${{ github.workspace }}

      - name: Install Purple dependencies for MacOS
        run: |
          ./install_purple_dependencies.command

      - name: Zip entire Purple folder (Mac)
        run: |
          zip purple-hats-portable-mac.zip -y -r ./
      
      - name: Upload Mac artifact
        uses: actions/upload-artifact@v3
        with:
          name: purple-hats-portable-mac
          path: ./purple-hats-portable-mac.zip
          
      - name: Release Mac artifact
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            purple-hats-portable-mac.zip
